// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: roveretoexplorer.proto

package eu.trentorise.smartcampus.service.roveretoexplorer.data.message;

public final class Roveretoexplorer {
  private Roveretoexplorer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventoRoveretoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string id = 1;
    boolean hasId();
    String getId();
    
    // required string titolo = 2;
    boolean hasTitolo();
    String getTitolo();
    
    // required string descrizione = 3;
    boolean hasDescrizione();
    String getDescrizione();
    
    // optional string image = 4;
    boolean hasImage();
    String getImage();
    
    // optional int64 fromTime = 5;
    boolean hasFromTime();
    long getFromTime();
    
    // optional int64 toTime = 6;
    boolean hasToTime();
    long getToTime();
    
    // optional double lat = 7;
    boolean hasLat();
    double getLat();
    
    // optional double lon = 8;
    boolean hasLon();
    double getLon();
    
    // required .eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Address indirizzo = 9;
    boolean hasIndirizzo();
    eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address getIndirizzo();
    eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.AddressOrBuilder getIndirizzoOrBuilder();
    
    // required string url = 10;
    boolean hasUrl();
    String getUrl();
    
    // required string tipo = 11;
    boolean hasTipo();
    String getTipo();
    
    // required string fonte = 12;
    boolean hasFonte();
    String getFonte();
    
    // required string whenWhere = 13;
    boolean hasWhenWhere();
    String getWhenWhere();
  }
  public static final class EventoRovereto extends
      com.google.protobuf.GeneratedMessage
      implements EventoRoveretoOrBuilder {
    // Use EventoRovereto.newBuilder() to construct.
    private EventoRovereto(Builder builder) {
      super(builder);
    }
    private EventoRovereto(boolean noInit) {}
    
    private static final EventoRovereto defaultInstance;
    public static EventoRovereto getDefaultInstance() {
      return defaultInstance;
    }
    
    public EventoRovereto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_EventoRovereto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_EventoRovereto_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          id_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string titolo = 2;
    public static final int TITOLO_FIELD_NUMBER = 2;
    private java.lang.Object titolo_;
    public boolean hasTitolo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getTitolo() {
      java.lang.Object ref = titolo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          titolo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTitoloBytes() {
      java.lang.Object ref = titolo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        titolo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string descrizione = 3;
    public static final int DESCRIZIONE_FIELD_NUMBER = 3;
    private java.lang.Object descrizione_;
    public boolean hasDescrizione() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDescrizione() {
      java.lang.Object ref = descrizione_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          descrizione_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDescrizioneBytes() {
      java.lang.Object ref = descrizione_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        descrizione_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string image = 4;
    public static final int IMAGE_FIELD_NUMBER = 4;
    private java.lang.Object image_;
    public boolean hasImage() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getImage() {
      java.lang.Object ref = image_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          image_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional int64 fromTime = 5;
    public static final int FROMTIME_FIELD_NUMBER = 5;
    private long fromTime_;
    public boolean hasFromTime() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getFromTime() {
      return fromTime_;
    }
    
    // optional int64 toTime = 6;
    public static final int TOTIME_FIELD_NUMBER = 6;
    private long toTime_;
    public boolean hasToTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getToTime() {
      return toTime_;
    }
    
    // optional double lat = 7;
    public static final int LAT_FIELD_NUMBER = 7;
    private double lat_;
    public boolean hasLat() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public double getLat() {
      return lat_;
    }
    
    // optional double lon = 8;
    public static final int LON_FIELD_NUMBER = 8;
    private double lon_;
    public boolean hasLon() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    public double getLon() {
      return lon_;
    }
    
    // required .eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Address indirizzo = 9;
    public static final int INDIRIZZO_FIELD_NUMBER = 9;
    private eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address indirizzo_;
    public boolean hasIndirizzo() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    public eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address getIndirizzo() {
      return indirizzo_;
    }
    public eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.AddressOrBuilder getIndirizzoOrBuilder() {
      return indirizzo_;
    }
    
    // required string url = 10;
    public static final int URL_FIELD_NUMBER = 10;
    private java.lang.Object url_;
    public boolean hasUrl() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    public String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          url_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string tipo = 11;
    public static final int TIPO_FIELD_NUMBER = 11;
    private java.lang.Object tipo_;
    public boolean hasTipo() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    public String getTipo() {
      java.lang.Object ref = tipo_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          tipo_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTipoBytes() {
      java.lang.Object ref = tipo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        tipo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string fonte = 12;
    public static final int FONTE_FIELD_NUMBER = 12;
    private java.lang.Object fonte_;
    public boolean hasFonte() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    public String getFonte() {
      java.lang.Object ref = fonte_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          fonte_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getFonteBytes() {
      java.lang.Object ref = fonte_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        fonte_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required string whenWhere = 13;
    public static final int WHENWHERE_FIELD_NUMBER = 13;
    private java.lang.Object whenWhere_;
    public boolean hasWhenWhere() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    public String getWhenWhere() {
      java.lang.Object ref = whenWhere_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          whenWhere_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getWhenWhereBytes() {
      java.lang.Object ref = whenWhere_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        whenWhere_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      id_ = "";
      titolo_ = "";
      descrizione_ = "";
      image_ = "";
      fromTime_ = 0L;
      toTime_ = 0L;
      lat_ = 0D;
      lon_ = 0D;
      indirizzo_ = eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.getDefaultInstance();
      url_ = "";
      tipo_ = "";
      fonte_ = "";
      whenWhere_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTitolo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescrizione()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIndirizzo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTipo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFonte()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasWhenWhere()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getTitoloBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDescrizioneBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getImageBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, fromTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, toTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeDouble(7, lat_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeDouble(8, lon_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeMessage(9, indirizzo_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getUrlBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getTipoBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeBytes(12, getFonteBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeBytes(13, getWhenWhereBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTitoloBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDescrizioneBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getImageBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, fromTime_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, toTime_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, lat_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, lon_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, indirizzo_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getUrlBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getTipoBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getFonteBytes());
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(13, getWhenWhereBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRoveretoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_EventoRovereto_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_EventoRovereto_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIndirizzoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        titolo_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        descrizione_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        image_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        fromTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        toTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000040);
        lon_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000080);
        if (indirizzoBuilder_ == null) {
          indirizzo_ = eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.getDefaultInstance();
        } else {
          indirizzoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        url_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        tipo_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        fonte_ = "";
        bitField0_ = (bitField0_ & ~0x00000800);
        whenWhere_ = "";
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto build() {
        eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto buildPartial() {
        eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto result = new eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.titolo_ = titolo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.descrizione_ = descrizione_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.image_ = image_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.fromTime_ = fromTime_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.toTime_ = toTime_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.lon_ = lon_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        if (indirizzoBuilder_ == null) {
          result.indirizzo_ = indirizzo_;
        } else {
          result.indirizzo_ = indirizzoBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.url_ = url_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.tipo_ = tipo_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.fonte_ = fonte_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.whenWhere_ = whenWhere_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto) {
          return mergeFrom((eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto other) {
        if (other == eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTitolo()) {
          setTitolo(other.getTitolo());
        }
        if (other.hasDescrizione()) {
          setDescrizione(other.getDescrizione());
        }
        if (other.hasImage()) {
          setImage(other.getImage());
        }
        if (other.hasFromTime()) {
          setFromTime(other.getFromTime());
        }
        if (other.hasToTime()) {
          setToTime(other.getToTime());
        }
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLon()) {
          setLon(other.getLon());
        }
        if (other.hasIndirizzo()) {
          mergeIndirizzo(other.getIndirizzo());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasTipo()) {
          setTipo(other.getTipo());
        }
        if (other.hasFonte()) {
          setFonte(other.getFonte());
        }
        if (other.hasWhenWhere()) {
          setWhenWhere(other.getWhenWhere());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasTitolo()) {
          
          return false;
        }
        if (!hasDescrizione()) {
          
          return false;
        }
        if (!hasIndirizzo()) {
          
          return false;
        }
        if (!hasUrl()) {
          
          return false;
        }
        if (!hasTipo()) {
          
          return false;
        }
        if (!hasFonte()) {
          
          return false;
        }
        if (!hasWhenWhere()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              titolo_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              descrizione_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              image_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              fromTime_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              toTime_ = input.readInt64();
              break;
            }
            case 57: {
              bitField0_ |= 0x00000040;
              lat_ = input.readDouble();
              break;
            }
            case 65: {
              bitField0_ |= 0x00000080;
              lon_ = input.readDouble();
              break;
            }
            case 74: {
              eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.Builder subBuilder = eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.newBuilder();
              if (hasIndirizzo()) {
                subBuilder.mergeFrom(getIndirizzo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setIndirizzo(subBuilder.buildPartial());
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              url_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              tipo_ = input.readBytes();
              break;
            }
            case 98: {
              bitField0_ |= 0x00000800;
              fonte_ = input.readBytes();
              break;
            }
            case 106: {
              bitField0_ |= 0x00001000;
              whenWhere_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string id = 1;
      private java.lang.Object id_ = "";
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setId(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      void setId(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
      }
      
      // required string titolo = 2;
      private java.lang.Object titolo_ = "";
      public boolean hasTitolo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getTitolo() {
        java.lang.Object ref = titolo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          titolo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTitolo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        titolo_ = value;
        onChanged();
        return this;
      }
      public Builder clearTitolo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        titolo_ = getDefaultInstance().getTitolo();
        onChanged();
        return this;
      }
      void setTitolo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        titolo_ = value;
        onChanged();
      }
      
      // required string descrizione = 3;
      private java.lang.Object descrizione_ = "";
      public boolean hasDescrizione() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDescrizione() {
        java.lang.Object ref = descrizione_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          descrizione_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDescrizione(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        descrizione_ = value;
        onChanged();
        return this;
      }
      public Builder clearDescrizione() {
        bitField0_ = (bitField0_ & ~0x00000004);
        descrizione_ = getDefaultInstance().getDescrizione();
        onChanged();
        return this;
      }
      void setDescrizione(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        descrizione_ = value;
        onChanged();
      }
      
      // optional string image = 4;
      private java.lang.Object image_ = "";
      public boolean hasImage() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getImage() {
        java.lang.Object ref = image_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          image_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setImage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        image_ = value;
        onChanged();
        return this;
      }
      public Builder clearImage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        image_ = getDefaultInstance().getImage();
        onChanged();
        return this;
      }
      void setImage(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000008;
        image_ = value;
        onChanged();
      }
      
      // optional int64 fromTime = 5;
      private long fromTime_ ;
      public boolean hasFromTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getFromTime() {
        return fromTime_;
      }
      public Builder setFromTime(long value) {
        bitField0_ |= 0x00000010;
        fromTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearFromTime() {
        bitField0_ = (bitField0_ & ~0x00000010);
        fromTime_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 toTime = 6;
      private long toTime_ ;
      public boolean hasToTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getToTime() {
        return toTime_;
      }
      public Builder setToTime(long value) {
        bitField0_ |= 0x00000020;
        toTime_ = value;
        onChanged();
        return this;
      }
      public Builder clearToTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        toTime_ = 0L;
        onChanged();
        return this;
      }
      
      // optional double lat = 7;
      private double lat_ ;
      public boolean hasLat() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public double getLat() {
        return lat_;
      }
      public Builder setLat(double value) {
        bitField0_ |= 0x00000040;
        lat_ = value;
        onChanged();
        return this;
      }
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000040);
        lat_ = 0D;
        onChanged();
        return this;
      }
      
      // optional double lon = 8;
      private double lon_ ;
      public boolean hasLon() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      public double getLon() {
        return lon_;
      }
      public Builder setLon(double value) {
        bitField0_ |= 0x00000080;
        lon_ = value;
        onChanged();
        return this;
      }
      public Builder clearLon() {
        bitField0_ = (bitField0_ & ~0x00000080);
        lon_ = 0D;
        onChanged();
        return this;
      }
      
      // required .eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Address indirizzo = 9;
      private eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address indirizzo_ = eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address, eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.Builder, eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.AddressOrBuilder> indirizzoBuilder_;
      public boolean hasIndirizzo() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      public eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address getIndirizzo() {
        if (indirizzoBuilder_ == null) {
          return indirizzo_;
        } else {
          return indirizzoBuilder_.getMessage();
        }
      }
      public Builder setIndirizzo(eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address value) {
        if (indirizzoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          indirizzo_ = value;
          onChanged();
        } else {
          indirizzoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder setIndirizzo(
          eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.Builder builderForValue) {
        if (indirizzoBuilder_ == null) {
          indirizzo_ = builderForValue.build();
          onChanged();
        } else {
          indirizzoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder mergeIndirizzo(eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address value) {
        if (indirizzoBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              indirizzo_ != eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.getDefaultInstance()) {
            indirizzo_ =
              eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.newBuilder(indirizzo_).mergeFrom(value).buildPartial();
          } else {
            indirizzo_ = value;
          }
          onChanged();
        } else {
          indirizzoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      public Builder clearIndirizzo() {
        if (indirizzoBuilder_ == null) {
          indirizzo_ = eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.getDefaultInstance();
          onChanged();
        } else {
          indirizzoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      public eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.Builder getIndirizzoBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getIndirizzoFieldBuilder().getBuilder();
      }
      public eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.AddressOrBuilder getIndirizzoOrBuilder() {
        if (indirizzoBuilder_ != null) {
          return indirizzoBuilder_.getMessageOrBuilder();
        } else {
          return indirizzo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address, eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.Builder, eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.AddressOrBuilder> 
          getIndirizzoFieldBuilder() {
        if (indirizzoBuilder_ == null) {
          indirizzoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address, eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.Builder, eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.AddressOrBuilder>(
                  indirizzo_,
                  getParentForChildren(),
                  isClean());
          indirizzo_ = null;
        }
        return indirizzoBuilder_;
      }
      
      // required string url = 10;
      private java.lang.Object url_ = "";
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      public String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setUrl(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        url_ = value;
        onChanged();
        return this;
      }
      public Builder clearUrl() {
        bitField0_ = (bitField0_ & ~0x00000200);
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      void setUrl(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000200;
        url_ = value;
        onChanged();
      }
      
      // required string tipo = 11;
      private java.lang.Object tipo_ = "";
      public boolean hasTipo() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      public String getTipo() {
        java.lang.Object ref = tipo_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          tipo_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTipo(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        tipo_ = value;
        onChanged();
        return this;
      }
      public Builder clearTipo() {
        bitField0_ = (bitField0_ & ~0x00000400);
        tipo_ = getDefaultInstance().getTipo();
        onChanged();
        return this;
      }
      void setTipo(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000400;
        tipo_ = value;
        onChanged();
      }
      
      // required string fonte = 12;
      private java.lang.Object fonte_ = "";
      public boolean hasFonte() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      public String getFonte() {
        java.lang.Object ref = fonte_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          fonte_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setFonte(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000800;
        fonte_ = value;
        onChanged();
        return this;
      }
      public Builder clearFonte() {
        bitField0_ = (bitField0_ & ~0x00000800);
        fonte_ = getDefaultInstance().getFonte();
        onChanged();
        return this;
      }
      void setFonte(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000800;
        fonte_ = value;
        onChanged();
      }
      
      // required string whenWhere = 13;
      private java.lang.Object whenWhere_ = "";
      public boolean hasWhenWhere() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      public String getWhenWhere() {
        java.lang.Object ref = whenWhere_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          whenWhere_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setWhenWhere(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00001000;
        whenWhere_ = value;
        onChanged();
        return this;
      }
      public Builder clearWhenWhere() {
        bitField0_ = (bitField0_ & ~0x00001000);
        whenWhere_ = getDefaultInstance().getWhenWhere();
        onChanged();
        return this;
      }
      void setWhenWhere(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00001000;
        whenWhere_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.roveretoexplorer.data.message.EventoRovereto)
    }
    
    static {
      defaultInstance = new EventoRovereto(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.roveretoexplorer.data.message.EventoRovereto)
  }
  
  public interface AddressOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string place = 1;
    boolean hasPlace();
    String getPlace();
    
    // optional string street = 2;
    boolean hasStreet();
    String getStreet();
    
    // optional string town = 3;
    boolean hasTown();
    String getTown();
  }
  public static final class Address extends
      com.google.protobuf.GeneratedMessage
      implements AddressOrBuilder {
    // Use Address.newBuilder() to construct.
    private Address(Builder builder) {
      super(builder);
    }
    private Address(boolean noInit) {}
    
    private static final Address defaultInstance;
    public static Address getDefaultInstance() {
      return defaultInstance;
    }
    
    public Address getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_Address_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_Address_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string place = 1;
    public static final int PLACE_FIELD_NUMBER = 1;
    private java.lang.Object place_;
    public boolean hasPlace() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getPlace() {
      java.lang.Object ref = place_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          place_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getPlaceBytes() {
      java.lang.Object ref = place_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        place_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string street = 2;
    public static final int STREET_FIELD_NUMBER = 2;
    private java.lang.Object street_;
    public boolean hasStreet() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getStreet() {
      java.lang.Object ref = street_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          street_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getStreetBytes() {
      java.lang.Object ref = street_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        street_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string town = 3;
    public static final int TOWN_FIELD_NUMBER = 3;
    private java.lang.Object town_;
    public boolean hasTown() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getTown() {
      java.lang.Object ref = town_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          town_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getTownBytes() {
      java.lang.Object ref = town_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        town_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      place_ = "";
      street_ = "";
      town_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPlaceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getStreetBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getTownBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPlaceBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getStreetBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getTownBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_Address_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_Address_fieldAccessorTable;
      }
      
      // Construct using eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        place_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        street_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        town_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.getDescriptor();
      }
      
      public eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address getDefaultInstanceForType() {
        return eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.getDefaultInstance();
      }
      
      public eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address build() {
        eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address buildPartial() {
        eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address result = new eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.place_ = place_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.street_ = street_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.town_ = town_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address) {
          return mergeFrom((eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address other) {
        if (other == eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.getDefaultInstance()) return this;
        if (other.hasPlace()) {
          setPlace(other.getPlace());
        }
        if (other.hasStreet()) {
          setStreet(other.getStreet());
        }
        if (other.hasTown()) {
          setTown(other.getTown());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              place_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              street_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              town_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string place = 1;
      private java.lang.Object place_ = "";
      public boolean hasPlace() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getPlace() {
        java.lang.Object ref = place_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          place_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setPlace(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        place_ = value;
        onChanged();
        return this;
      }
      public Builder clearPlace() {
        bitField0_ = (bitField0_ & ~0x00000001);
        place_ = getDefaultInstance().getPlace();
        onChanged();
        return this;
      }
      void setPlace(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        place_ = value;
        onChanged();
      }
      
      // optional string street = 2;
      private java.lang.Object street_ = "";
      public boolean hasStreet() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getStreet() {
        java.lang.Object ref = street_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          street_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setStreet(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        street_ = value;
        onChanged();
        return this;
      }
      public Builder clearStreet() {
        bitField0_ = (bitField0_ & ~0x00000002);
        street_ = getDefaultInstance().getStreet();
        onChanged();
        return this;
      }
      void setStreet(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        street_ = value;
        onChanged();
      }
      
      // optional string town = 3;
      private java.lang.Object town_ = "";
      public boolean hasTown() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getTown() {
        java.lang.Object ref = town_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          town_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setTown(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        town_ = value;
        onChanged();
        return this;
      }
      public Builder clearTown() {
        bitField0_ = (bitField0_ & ~0x00000004);
        town_ = getDefaultInstance().getTown();
        onChanged();
        return this;
      }
      void setTown(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        town_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Address)
    }
    
    static {
      defaultInstance = new Address(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Address)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_EventoRovereto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_EventoRovereto_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_Address_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_Address_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026roveretoexplorer.proto\022?eu.trentorise." +
      "smartcampus.service.roveretoexplorer.dat" +
      "a.message\032\ncore.proto\"\246\002\n\016EventoRovereto" +
      "\022\n\n\002id\030\001 \002(\t\022\016\n\006titolo\030\002 \002(\t\022\023\n\013descrizi" +
      "one\030\003 \002(\t\022\r\n\005image\030\004 \001(\t\022\020\n\010fromTime\030\005 \001" +
      "(\003\022\016\n\006toTime\030\006 \001(\003\022\013\n\003lat\030\007 \001(\001\022\013\n\003lon\030\010" +
      " \001(\001\022[\n\tindirizzo\030\t \002(\0132H.eu.trentorise." +
      "smartcampus.service.roveretoexplorer.dat" +
      "a.message.Address\022\013\n\003url\030\n \002(\t\022\014\n\004tipo\030\013" +
      " \002(\t\022\r\n\005fonte\030\014 \002(\t\022\021\n\twhenWhere\030\r \002(\t\"6",
      "\n\007Address\022\r\n\005place\030\001 \001(\t\022\016\n\006street\030\002 \001(\t" +
      "\022\014\n\004town\030\003 \001(\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_EventoRovereto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_EventoRovereto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_EventoRovereto_descriptor,
              new java.lang.String[] { "Id", "Titolo", "Descrizione", "Image", "FromTime", "ToTime", "Lat", "Lon", "Indirizzo", "Url", "Tipo", "Fonte", "WhenWhere", },
              eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto.class,
              eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.EventoRovereto.Builder.class);
          internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_Address_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_Address_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eu_trentorise_smartcampus_service_roveretoexplorer_data_message_Address_descriptor,
              new java.lang.String[] { "Place", "Street", "Town", },
              eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.class,
              eu.trentorise.smartcampus.service.roveretoexplorer.data.message.Roveretoexplorer.Address.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          it.sayservice.platform.core.message.Core.getDescriptor(),
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
